### ISSUE TITLE
How to tell Delegation Selector Value to use tags that are not parented by certain other tags?

### ISSUE THREAD

**Issue by syberknight** [IonicaBizau/mini-lightbox#17] opened 2016-10-20 22:47 UTC
i'm needing to use the _**Delegation**_ method you provide for, but i'm not figuring out how to make it work for my situation...

_fyi, i know HTML/CSS, but i'm just learning JS/Jquery._

i'm wanting to have the lightbox work for **ALL** image within a section **EXCEPT** for images that are parented by an "**a href**" tag.

here's a partial example of my markup structure...

```
<article>
     <img>
     <div><img></div>
     <figure><img></figure>
     <a href><img></a>
     <figure><a href><img></a></figure>
</article>
```

this works fine for every image i can include a class or id to, but unfortunately, most will be coming in dynamically & my attempts to add a class or id to those img tag templates are being overwritten by the source _(Tumblr API)_...

```
window.onload = function () {
        MiniLightbox(".miniLightbox");
};
```

so then i tried this, and it works great! except, that some images i'm pulling in are navigational thumbnails for the photosets slideshows. those are the `<img>` tags with the `<a href>` parents. none of the larger/actual images that i want to light up will have any `<a>` tags. BUT they will be surrounded by a plethora of other tags (like div, figure, p, li, etc)...

```
window.onload = function () {
        MiniLightbox({
            selector: "article  img",
            delegation: "html"
        });
};
```

lastly, in researching how in jquery to select tags except for ones parented by others, i pieced together `article:not(:has(a)) img`, which seems to work in other scenarios, but not here where it's a **value string** _(getting my terminology right?)_...

```
window.onload = function () {
        MiniLightbox({
            selector: "article:not(:has(a)) img",
            delegation: "html"
        });
};
```

**so, any ideas how to accomplish getting the lightbox to work with...**
`<article> //anything// <img> //anything// </article>`
**...but NOT work on...**
`<article> //anything// <a href><img></a> //anything// </article>`
**...???**

THANKS SO MUCH!!!
-jason.

**Comment by IonicaBizau** [comment] 2016-10-21 09:09
Use the [`customOpen` hook](https://github.com/IonicaBizau/mini-lightbox#advanced-usage):

```js
MiniLightbox.customOpen = function () {

    // Stop the open
    if (this.img.parentElement.tagName === "A") { return false; }

    this.box.classList.add("animated", "fadeIn");
    this.img.classList.add("animated", "fadeInUp");
};
```

Let me know how it works. 😁

**Comment by syberknight** [comment] 2016-10-22 00:35
hey. thanks for that. but i'm still not getting it to work (probably cause i just don't know what i'm doing)...

i have the `customClose` section & the `customOpen` section exactly copied out of your example/demo, along with the `window.onload = function (){...` section.

i put your `if` line in the `customOpen` section as you show above.
then do i leave the `onload` -> `selector` as `"article img"` or do i remove that altogether?

i tried it both ways. if i leave it as-is, nothing changes... still every image lights up.
if i remove the onload section or even just the selector line, the whole thing breaks.

thanks again for your help!

**Comment by syberknight** [comment] 2016-10-22 00:59
btw, in case it's helpful, here's my entire codeblock for this...

```
<script>
    MiniLightbox.customClose = function () {
        var self = this;
        self.img.classList.add("animated", "fadeOutDown");
        setTimeout(function () {
            self.box.classList.add("animated", "fadeOut");
            setTimeout(function () {
                self.box.classList.remove("animated", "fadeOut");
                self.img.classList.remove("animated", "fadeOutDown");
                self.box.style.display = "none";
            }, 500);
        }, 500);
        return false;
    };

    MiniLightbox.customOpen = function () {

        if (this.img.parentElement.tagName === "A") { return false; }
    
        this.box.classList.add("animated", "fadeIn");
        this.img.classList.add("animated", "fadeInUp");
    };

    window.onload = function () {
        MiniLightbox({
            selector: "article img",
            delegation: "html"
        });
    };
</script>
```
...could it matter where in the page this is located (head, body, above, below, etc)?

**Comment by IonicaBizau** [comment] 2016-10-22 16:06
Can you share a full example (e.g. JSBin or JSFiddle) to reproduce the issue?

**Comment by syberknight** [comment] 2016-10-23 05:52
hey, apologies for the delay.

here's a playground i just put together of it... http://codepen.io/syberknight/pen/qagbkW

i appreciate your time.
-jason.

**Comment by IonicaBizau** [comment] 2016-10-23 07:11
Ah, actually it's a bug in the library because we always `preventDefault` the click event.

**Comment by syberknight** [comment] 2016-10-24 00:04
OH! well... any temporary workarounds i can do for now?

**Comment by IonicaBizau** [comment] 2016-10-24 02:08
Not really, we just have to fix it somewhere [here](https://github.com/IonicaBizau/mini-lightbox/blob/95e080c49dbbf382e70858545ffad57c388edb5f/lib/index.js#L86).

**Comment by syberknight** [comment] 2016-10-24 23:31
ok. any kind of timetable on that? just wondering what to expect. should i try to find another solution or is this something you're actively working on?
with respect,
-jason.

**Comment by IonicaBizau** [comment] 2016-10-25 18:13
@syberknight Would you like to contribute to it?

I'd be happy to merge a pull request.

Btw, not sure if you know this: https://hacktoberfest.digitalocean.com/ :grin:

**Comment by syberknight** [comment] 2016-10-25 21:20
my apologies for my ignorance (i'm learning), but what do you mean by "merge a pull request"?

and no, i didn't/don't know anything about hacktoberfest. i'll check out the link but i'm by no means anywhere near hacker level programming. i know HTML/CSS but am just now starting to skim the surfaces of JS/Jquery & PHP.
thanks!

**Comment by IonicaBizau** [comment] 2016-10-26 17:00
I see! Will probably take care of this these days. Hopefully next week this time it will be fixed.

**Comment by syberknight** [comment] 2016-11-13 03:30
hiho, just checking in to see if/how this is going.
much appreciation!

**Comment by IonicaBizau** [comment] 2016-11-22 14:31
@syberknight Whoups! Totally forgot about this one! So, sorry. Do you still want to do it? Probably I can find time to fix it.

**Comment by syberknight** [comment] 2016-11-22 16:32
yes yes yes pullease! ;-)
didn't wanna be too pushy, but yeah, i could still use help on this.
THANK YOU!!!

**Comment by IonicaBizau** [comment] 2016-12-19 11:18
I'm finally on it.

**Closed** 2016-12-19 12:45 UTC
Labels: bug
